spring:
  application:
    name: oauth2
  security:
    oauth2:
      authorization-server:
        issuer: http://localhost:8080    

oauth2:
  public-key-pem-base64: ${PUBLIC_KEY_PEM_BASE64:}
  private-key-pem-base64: ${PRIVATE_KEY_PEM_BASE64:}
  authorized-clients-yaml-base64: ${AUTHORIZED_CLIENTS_YAML_BASE64:}

server:
  port: 8080
  ssl:
    enabled: false
